version: "3.9"
services:
  nginx_categorize:
    container_name: nginx_categorize
    image: nginx:1.17.8
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www
    links:
      - php_categorize
  php_categorize:
    container_name: php_categorize
    image: php:7.4-fpm
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
